---
name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    needs:
      - lint
      - test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Build and test with Rake
        run: |
          bundle exec rake release
        with:
          api_key: ${{secrets.RUBYGEMS_API_KEY}}
